# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'adPractice' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for adPractice
pod 'Firebase/AdMob'
pod 'Firebase/Core'
pod 'Firebase'

  target 'adPracticeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'adPracticeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
