# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'usingJSON' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for usingJSON
pod 'SwiftyJSON'
pod 'Freddy'
pod 'Gloss', '~>1.2'

  target 'usingJSONTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'usingJSONUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
